Create DATABASE URCAMWPDB

USE URCAMWPDB

-- update USUARIO set ADMINISTRADOR = 1 where IDUSUARIO = 1
-- insert into USUARIO (NOMBRE,APELLIDO,CORREO,CONTRASE�A,ADMINISTRADOR) values ('Gus', 'Valadez', 'gus@hotmail.com', '123', '0')

drop table USUARIO

CREATE TABLE USUARIO 
(
IDUSUARIO INT PRIMARY KEY Auto_increment,
NOMBRE VARCHAR(100) NOT NULL,
APELLIDO VARCHAR(100) NOT NULL,
CORREO VARCHAR(100) NOT NULL,
CONTRASENA VARCHAR(100) NOT NULL,
ADMINISTRADOR BIT
)

-- SELECT * FROM USUARIO
-- SELECT * FROM PRODUCTO

-- insert into PRODUCTO (NOMPROD,CARACTR,DESCRIPCION,URLIMAGEN,PRECIO,STOCK) values ('Extintor', 'CO2', '8kg', 'CO2.png',1200, 100)

CREATE TABLE PRODUCTO 
(
IDPRODUCTO INT PRIMARY KEY Auto_increment,
NOMPROD VARCHAR(100) NOT NULL,
CARACTR VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR (500) NOT NULL,
URLIMAGEN VARCHAR(100),
PRECIO DECIMAL (10,0),
STOCK INT,
FECHAREG DATETIME DEFAULT
)

CREATE TABLE COMPRA
(
IDCOMPRA INT PRIMARY KEY Auto_increment,
IDUSUARIO INT REFERENCES USUARIO(IDUSUARIO),
NOMBRE VARCHAR(100),
APELLIDO VARCHAR(100),
CANTCOMP INT NOT NULL,
TOTAL DECIMAL(10,2) NOT NULL,
DIRECCION VARCHAR(400) NOT NULL,
FECHACOMPRA DATE DEFAULT
)

CREATE TABLE DETALLECOMPRA
(
IDDETALLECOMPRA INT PRIMARY KEY Auto_increment,
IDCOMPRA INT REFERENCES COMPRA(IDCOMPRA),
IDPRODUCTO INT REFERENCES PRODUCTO(IDPRODUCTO),
CANTIDAD INT NOT NULL,
TOTAL DECIMAL(10,2) NOT NULL
)

-- insert into CARRITO (IDUSUARIO,IDPRODUCTO) values (1,2)
-- insert into CARRITO (IDUSUARIO,IDPRODUCTO) values (1,5)
-- insert into CARRITO (IDUSUARIO,IDPRODUCTO) values (2,2)

-- SELECT * FROM CARRITO
-- SELECT * FROM COMPRA
-- select * from DETALLECARRITO
-- delete from COMPRA
-- delete from DETALLECOMPRA
-- delete from DETALLECARRITO
-- delete from USUARIO
-- delete from CARRITO
-- delete from PRODUCTO
-- SELECT * FROM DETALLECOMPRA

CREATE TABLE CARRITO
(
IDCARRITO INT PRIMARY KEY Auto_increment,
IDUSUARIO INT REFERENCES USUARIO(IDUSUARIO),
IDPRODUCTO INT REFERENCES PRODUCTO(IDPRODUCTO)
)

-- insert into CARRITO 

CREATE TABLE DETALLECARRITO
(
IDDETALLECARRITO INT PRIMARY KEY Auto_increment,
IDCARRITO INT REFERENCES CARRITO(IDCARRITO),
IDPRODUCTO INT REFERENCES PRODUCTO(IDPRODUCTO),
CANTIDAD INT 
)

